### ISSUE TITLE
FFMPEG download fails on initial run

### ISSUE THREAD

**Issue by jeremymeyers** [cooperdk/YAPO-e-plus#56]
I can only assume this is because you are redoing your website, but the initial run tries to pull FFMPEG and fails.

error:

"I am going to install a copy of FFPMEG (4.3.1 static, YAPO build).
It will be placed at C:\YAPO\videos\ffmpeg
Press enter to acknowledge... >
Getting https://porn-organizer.org/dl/ffmpeg-latest.zip...
Downloading...
Copying ffmpegC:\YAPO\videos\ffmpeg\https:\porn-organizer.org\dl\ffmpeg-latest\bin\ffmpeg.exe
An error occured, please download FFMPEG manually from the above link
and place it in C:\YAPO\videos\ffmpeg
YAPO will exit now. Press enter to acknowledge... >"

**Comment by jeremymeyers** [comment]
(also just noticed that it seems to have downloaded and installed FFMpeg so maybe this is more of a case of an incorrect error parsing?)

**Comment by cooperdk** [comment]
I haven't experienced issues when testing YAPO. It's tested manually, there's no real unit testing of the app right now.

But I have never experienced that it reported an error when placing the file.

HOWEVER, the way the function is written now, it will error out if YAPO is not allowed to delete the temporary directory it generates when unpacking ffmpeg/ffprobe.

It should be in the C:\YAPO\videos\ffmpeg folder and named ffmpeg-latest.zip

If it's there, then it is because YAPO (Python) doesn't have sufficient privileges to remove the zip file.

Could you tell me if it is still in there? If so, I will change the script a bit so it removes as a separate routine in the function and only give an error if it cannot remove that zip file.

**Comment by cooperdk** [comment]
I found out what caused this issue. The error was caused by an updated Python module which changed from not automatically unpacking and moving zip files to doing so. This is why the files were placed correctly even though an error was printed.

The function has now been modified to support the new module.
