### ISSUE TITLE
Contact Sheet generation fails

### ISSUE THREAD

**Issue by jeremymeyers** [cooperdk/YAPO-e-plus#57]
Getting an error when scanning:

"Generating Contact Sheet (1024 px wide, grid: 4x4...
Processing M:\Alice Bell - gush.iscreamgirls.14.08.06.alice.bell.mp4...
[ERROR] Could not find 'ffprobe' executable. Please make sure ffmpeg/ffprobe is installed and is in your PATH.
Error creating contact sheet!"

ffprobe.exe exists in C:\YAPO\videos\ffmpeg and lauches correctly from the command line (without any errors, i mean)

**Comment by cooperdk** [comment]
Oh, this is a bug "on me". The reason is that the videosheet script looks for ffmpeg and ffprobe within the Windows path list.
I have to change that script to look in YAPO/videos/ffmpeg on Windows. I didn't notice that error because I have ffmpeg/ffprobe in the Windows paths.

For now, you can copy those two to C:\Windows\System32 and it will work. I will mark the change to high priority and fix it ASAP. Thanks for letting me know! :-)

**Comment by jeremymeyers** [comment]
ffmpeg seems to work, just not ffprobe, just for additional info. though its possible that i have a ffmpeg in a path directory.

**Comment by jeremymeyers** [comment]
BTW here's how to do it via windows GUI (win doesn't let you add to the system32 folder easily at all, for good reason) https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/  ... i believe they are held in the registry: https://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-windows-command-line-and-registry/

**Comment by cooperdk** [comment]
I believe you have a copy of ffmpeg somewhere in your paths because YAPO looked for it there.

I have now fixed the sheet generator and a working version will be included in the next update which will be uploaded in a few days. 

I'd like YAPO to use it's own binaries because some variants of ffmpeg/ffprobe may be missing important components.
FX, I have seen ffprobe fail at probing due to a bad compile. Also, I am going to make a x.265/HEVC transcoder at some point as it will save a lot of disk space and that requires a build of FFPMEG which has x.265 included (which my own has).
