### ISSUE TITLE
Scene scan doesn't differentiate between 'not found' and 'found but force is not checked'

### ISSUE THREAD

**Issue by jeremymeyers** [cooperdk/YAPO-e-plus#58]
As above, when scanning for a title that has already been scanned (and misidentified), the console shows 'has already been scanned' and the web GUI shows 'not found'. clicking 'force' will replace existing info.

**Comment by cooperdk** [comment]
This is by design.
The scanned and misidentified titles are marked with the tag "TpDB: Questionable" (as far as I remember) which allows you to re-scan them individually.
If you choose "force" when re-scanning individually, it will always replace all of the information, this is because the information on TpDB may improve.

If you have an idea to how this could be done better, I'd be happy to take a look at it.

**Comment by jeremymeyers** [comment]
this makes sense it's just that the error message (in the yellow box) is the same for bothOn Dec 26, 2020 4:32 PM, cooperdk <notifications@github.com> wrote:
This is by design.
The scanned and misidentified titles are marked with the tag "TpDB: Questionable" (as far as I remember) which allows you to re-scan them individually.
If you choose "force" when re-scanning individually, it will always replace all of the information, this is because the information on TpDB may improve.
If you have an idea to how this could be done better, I'd be happy to take a look at it.

**Comment by cooperdk** [comment]
Yes, the yellow box displays messages about something that's not really an error, but not really a success either. For actual errors, the box will be red, and for completed tasks with a successful outcome it will be green.

**Comment by cooperdk** [comment]
I have given this some thought, and since I have now found out how to pass a message from the Django backend to the user interface, I will sort out how to implement a message if a scene was scanned successfully or if the scene was not found or if it was found but already scanned (with different status colors).

**Comment by cooperdk** [comment]
Differentiation between "not found" and "found, but already scanned and force is disabled" now works.

The former is handled witha 404 from the backend, and the latter with a 403, which is picked up by the user interface.
