### ISSUE TITLE
[Bug Report] Folder re-scanning will re-add scenes previously removed from database

### ISSUE THREAD

**Issue by jeremymeyers** [cooperdk/YAPO-e-plus#59]
As above, hitting "Rescan folder" will add scenes that have been removed via the trash button. (guess you would need to keep track of hashes that have been removed)

**Comment by cooperdk** [comment]
This is also by design. YAPO expects you to move files away from the directories it should scan if you don't want files to be added. The "trash" button is meant to remove all information about a scene from the system so that it can be re-scanned. An alternative is to let YAPO delete the file as well, which is done by choosing to select multiple files and then clicking on the "fire" icon.

If you wish, I could add a field to disable files from scanning, but it makes no sense to let YAPO scan folders with files it shouldn't scan and track.
