### ISSUE TITLE
400 Error When Scraping TPDB

### ISSUE THREAD

**Issue by jason4bury** [cooperdk/YAPO-e-plus#84]
Whenever I try to scan a scene using the TPDB the following appears -

[WARN!] api.metadataapi.net returns an unexpected reply code: 400

- and the scan does not take place.

**Comment by cooperdk** [comment]
This is likely a non-bug. You should register your TpDB API key in settings > TpDB Scanning. If you do not, the TpDB scanner will not work. You can turn it off if you don't wish to register a free TpDB account.

**Comment by jason4bury** [comment]
I cannot see anywhere on that page when I can enter my API key. Where can I find it?

I'm using version 0.7.6.4

**Comment by cooperdk** [comment]
It is not there then. You will need to update YAPO. The latest release (compiled) version has the API field in settings.
Otherwise, download it from here: https://porn-organizer.org/dl/yapo-eplus.exe

The Github source version is always up-to-date, if you prefer to run YAPO with your own Python installation.
 

Fra: Jason Rhodes ***@***.***> 
Sendt: 1. september 2021 23:49
Til: cooperdk/YAPO-e-plus ***@***.***>
Cc: cooperdk ***@***.***>; Assign ***@***.***>
Emne: Re: [cooperdk/YAPO-e-plus] 400 Error When Scraping TPDB (#84)

 

I cannot see anywhere on that page when I can enter my API key. Where can I find it?

I'm using version 0.7.6.4

**Comment by cooperdk** [comment]
The API field was found not in place in the last compile, for some reason.
I advise you to update YAPO from source, until I can compile a new release. The zip on https://porn-organizer.org/dl is updated, but not the exe.
